### ISSUE TITLE
[ADR] Error when client starts halfway through server init

### ISSUE THREAD

**Issue by roboguy222** [McDermott-Group/servers#22]
`Unhandled error in message listener: MessageContext(source=1, ID=(0L,0L), target=102,) ($L, ('message',False)) ((function <lambda> at 0x0482345>, (), {})`

**Comment by roboguy222** [comment]
This seems to be another issue where the server sends a "server"connected" named message  before actually being connected.  See post in #21.

**Comment by roboguy222** [comment]
Clicking ADR3 in the dropdown goes to a normal working state.

**Comment by patzinak** [comment]
@roboguy222 Is this bug still relevant?

**Comment by roboguy222** [comment]
Sure, this error often appears once or twice.  Not sure how to go about fixing it though.

**Comment by patzinak** [comment]
Here is the relevant part of the log. Experienced the failed startup two times out of four or so attempts.

```
2016-10-14 01:55:38-0500 [LabradProtocol,client] ADR3 starting...
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Server running for Heat Switch.

2016-10-14 01:55:38-0500 [-] [log] Server running for Compressor.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Server running for Diode Temperature Monitor.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Server running for Ruox Temperature Monitor.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Server running for Power Supply.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Server running for Magnet Voltage Monitor.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Compressor connected.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Diode Temperature Monitor connected.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Power Supply connected.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] Magnet Voltage Monitor connected.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] [log] No devices connected for Ruox Temperature Monitor.
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [-] Unhandled error in Deferred:

2016-10-14 01:55:38-0500 [-] Unhandled Error

    Traceback (most recent call last):

    Failure: labrad.types.Error: (0) [AC Bridge with Multiplexer] Remote Traceback (most recent call last):

      File "C:\Python27\lib\site-packages\labrad\server.py", line 232, in request_handler

        result = yield setting.handleRequest(self, c.data, flat_data)

      File "C:\Python27\lib\site-packages\labrad\decorators.py", line 181, in handleRequest

        return self.func(server, c, data)

      File "ac_bridge_with_multiplexer.py", line 115, in add_channel

        devChans = self.allDeviceChans[c['address']]

    exceptions.KeyError: 'address'

     [payload=None]



2016-10-14 01:55:38-0500 [-] Unhandled error in Deferred:

2016-10-14 01:55:38-0500 [-] Unhandled Error

    Traceback (most recent call last):

    Failure: labrad.types.Error: (0) [AC Bridge with Multiplexer] Remote Traceback (most recent call last):

      File "C:\Python27\lib\site-packages\labrad\server.py", line 232, in request_handler

        result = yield setting.handleRequest(self, c.data, flat_data)

      File "C:\Python27\lib\site-packages\labrad\decorators.py", line 181, in handleRequest

        return self.func(server, c, data)

      File "ac_bridge_with_multiplexer.py", line 115, in add_channel

        devChans = self.allDeviceChans[c['address']]

    exceptions.KeyError: 'address'

     [payload=None]
2016-10-14 01:55:38 - labrad.adr3: 2016-10-14 01:55:38-0500 [LabradProtocol,client] ADR3 now serving
2016-10-14 01:55:38 - labrad.mcd_adr3_serial_server: 2016-10-14 01:55:38-0500 [-] [SerialDevice(name='COM1', devicepath='\\\\.\\COM1'), SerialDevice(name='COM3', devicepath='\\\\.\\COM3'), SerialDevice(name='COM4', devicepath='\\\\.\\COM4'), SerialDevice(name='COM5', devicepath='\\\\.\\COM5'), SerialDevice(name='COM6', devicepath='\\\\.\\COM6'), SerialDevice(name='COM7', devicepath='\\\\.\\COM7'), SerialDevice(name='COM8', devicepath='\\\\.\\COM8'), SerialDevice(name='COM9', devicepath='\\\\.\\COM9'), SerialDevice(name='COM10', devicepath='\\\\.\\COM10'), SerialDevice(name='COM11', devicepath='\\\\.\\COM11')]
2016-10-14 01:55:39 - labrad.adr3: 2016-10-14 01:55:39-0500 [-] [log] Power Supply initialized.

2016-10-14 01:55:39-0500 [-] Unhandled error in Deferred:

2016-10-14 01:55:39-0500 [-] Unhandled Error

    Traceback (most recent call last):

    Failure: labrad.types.Error: (0) [AC Bridge with Multiplexer] Remote Traceback (most recent call last):

      File "C:\Python27\lib\site-packages\labrad\server.py", line 232, in request_handler

        result = yield setting.handleRequest(self, c.data, flat_data)

      File "C:\Python27\lib\site-packages\labrad\decorators.py", line 181, in handleRequest

        return self.func(server, c, data)

      File "ac_bridge_with_multiplexer.py", line 115, in add_channel

        devChans = self.allDeviceChans[c['address']]

    exceptions.KeyError: 'address'

     [payload=None]



2016-10-14 01:55:39-0500 [-] Unhandled error in Deferred:

2016-10-14 01:55:39-0500 [-] Unhandled Error

    Traceback (most recent call last):

    Failure: labrad.types.Error: (0) [AC Bridge with Multiplexer] Remote Traceback (most recent call last):

      File "C:\Python27\lib\site-packages\labrad\server.py", line 232, in request_handler

        result = yield setting.handleRequest(self, c.data, flat_data)

      File "C:\Python27\lib\site-packages\labrad\decorators.py", line 181, in handleRequest

        return self.func(server, c, data)

      File "ac_bridge_with_multiplexer.py", line 115, in add_channel

        devChans = self.allDeviceChans[c['address']]

    exceptions.KeyError: 'address'

     [payload=None]
2016-10-14 01:55:50 - labrad.mcd_adr3_serial_server: 2016-10-14 01:55:50-0500 [-] [SerialDevice(name='COM1', devicepath='\\\\.\\COM1'), SerialDevice(name='COM3', devicepath='\\\\.\\COM3'), SerialDevice(name='COM4', devicepath='\\\\.\\COM4'), SerialDevice(name='COM5', devicepath='\\\\.\\COM5'), SerialDevice(name='COM6', devicepath='\\\\.\\COM6'), SerialDevice(name='COM7', devicepath='\\\\.\\COM7'), SerialDevice(name='COM8', devicepath='\\\\.\\COM8'), SerialDevice(name='COM9', devicepath='\\\\.\\COM9'), SerialDevice(name='COM10', devicepath='\\\\.\\COM10'), SerialDevice(name='COM11', devicepath='\\\\.\\COM11')]
2016-10-14 01:55:50 - labrad.adr3: 2016-10-14 01:55:50-0500 [-] [log] Power Supply initialized.

2016-10-14 01:55:50-0500 [-] Unhandled error in Deferred:
```

**Comment by roboguy222** [comment]
I don't think this error has occurred in a while, and is a mute point if we are going to a web-based controller, so I'm going to close this.
